name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSaberPlaylistsLib/**'
      - '.github/workflows/BuildMaster.yml'
      - 'Refs/**'
  pull_request:
    branches: [ master ]
    paths: 'BeatSaberPlaylistsLib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['Release', 'Release-BeatSaber']
    env:
      Configuration: ${{ matrix.configuration }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
      if: matrix.configuration == 'Release-BeatSaber'
    - name: ExtractRefs
      run: unzip -q -n bsfiles.zip -d ./Refs
      if: matrix.configuration == 'Release-BeatSaber'
    - name: Build ${{ matrix.configuration }}
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet pack
    - name: Upload Lib Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ${{ steps.Build.outputs.artifactpath }}
    - name: Upload ${{ matrix.configuration }} Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ${{ steps.Build.outputs.artifactpath }}
    - name: Upload ${{ matrix.configuration }} Nuget
      uses: actions/upload-artifact@v2
      with:
        name: Nuget-${{ steps.Build.outputs.filename }}
        path: BeatSaberPlaylistsLib/bin/${{ matrix.configuration }}/*pkg
