name: Tagged-Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['Release', 'Release-BeatSaber']
    env:
      Configuration: ${{ matrix.configuration }}
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download SIRA References
      uses: ProjectSIRA/download-sira-stripped@1.0.0
      with:
        manifest: ${{github.workspace}}/BeatSaberPlaylistsLib.BeatSaber/manifest.json
        sira-server-code: ${{ secrets.SIRA_SERVER_CODE }}
    - name: Download Mod Dependencies
      uses: Goobwabber/download-beatmods-deps@1.2
      with:
        manifest: ${{github.workspace}}/BeatSaberPlaylistsLib.BeatSaber/manifest.json
    - name: Build ${{ matrix.configuration }}
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet build
    - name: Pack ${{ matrix.configuration }}
      id: Pack
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet pack
    - name: Echo
      run: echo ${{ steps.Build.outputs.zippath }}
    - name: Make Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        name: "${{ steps.Build.outputs.release-title }}"
        body_path: CHANGELOG.md
        draft: true
        files: |
          ${{ steps.Build.outputs.zippath }}
          ${{ steps.Build.outputs.projectdir }}bin/${{ matrix.configuration }}/*pkg
