name: Unit Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSaberPlaylistsLib/**'
      - 'Shared/**'
      - 'BeatSaberPlaylistsLibTests/**'
      - '.github/workflows/UnitTests.yml'
  pull_request:
    branches: [ master ]
    paths: 
      -'BeatSaberPlaylistsLib/**'
      -'BeatSaberPlaylistsLibTests/**'
    

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Test
      id: Test
      run: dotnet test --logger GitHubActions
